### ISSUE TITLE
Error: hals() got multiple values for keyword argument 'nnt'

### ISSUE THREAD

**Issue by pankajkgupta** [ikinsella/locaNMF#1]
Hi, I followed the instructions to get the demo notebook running. But the rank_linesearch function fails with the following error. I am using the cpu so far.
I am new to NMF and might be missing a minor thing but not sure at the moment.
Would you guys have any idea?
-Pankaj

> ---------------------------------------------------------------------------
>TypeError                                 Traceback (most recent call last)
><ipython-input-13-b1f60b752a3f> in <module>
>    16                                             verbose=[True, False, False],
>      17                                             sample_prop=(1,1),
> ---> 18                                             device=device
>      19                                          )
>      20 if device=='cuda': torch.cuda.synchronize()
> 
> ~/anaconda3/envs/locanmf/lib/python3.6/site-packages/locanmf-1.0-py3.6.egg/locanmf/LocaNMF.py in rank_linesearch(low_rank_video, region_metadata, region_lr_videos, rank_range, maxiter_rank, verbose, indent, device, **kwargs)
>     209                                  verbose=verbose[-1],
>     210                                  device=device,
> --> 211                                  **kwargs)
>     212         curr_ranks.append(len(region_factors[-1]))
>     213 
> 
> ~/anaconda3/envs/locanmf/lib/python3.6/site-packages/locanmf-1.0-py3.6.egg/locanmf/LocaNMF.py in init_from_low_rank_video(low_rank_video, factorization, num_components, verbose, indent, device, **kwargs)
>     313          nnt=False,
>     314          device=device,
> --> 315          **kwargs)
>     316 
>     317 
> 
> TypeError: hals() got multiple values for keyword argument 'nnt'

**Comment by pseudomanu** [comment]
Hi,
I have the same issue. I suspect it comes from the demo code being outdated. There seem to be a mismatch between the number of arguments for **rank_linesearch** in cell 13 and the number of arguments that this function expects: 
```
locanmf_comps = LocaNMF.rank_linesearch(low_rank_video,
                                            region_metadata,
                                            region_videos,
                                            maxiter_rank=maxrank-minrank+1,
                                            maxiter_lambda=20, 
                                            maxiter_hals=20,
                                            lambda_step=1.35,
                                            lambda_init=1e-6, 
                                            loc_thresh=loc_thresh,
                                            r2_thresh=r2_thresh,
                                            rank_range=rank_range,
                                            nnt=nonnegative_temporal,
                                            verbose=[True, False, False],
                                            sample_prop=(1,1),
                                            device=device
```

**Comment by ss5513** [comment]
Fixed! Please go through the installation process again.

**Comment by pseudomanu** [comment]
Thanks!
